### ISSUE TITLE
Traits cannot have constants

### ISSUE THREAD

**Issue by betterapp** [BrandOriented/SimpleRESTAdapterBundle#10]
### Pimcore version(s) affected

11

### Description

```
Symfony\Component\ErrorHandler\Error\FatalError^ {#4156
  #message: "Compile Error: Traits cannot have constants"
  #code: 0
  #file: "./vendor/bo-hub/ci-hub-api-bundle/src/Provider/Traits/HasBaseAssetProvider.php"
  #line: 32
  -error: array:4 [
    "type" => 64
    "message" => "Traits cannot have constants"
```

### How to reproduce

The error is showing up in PHP 8.1
const in trait are available from PHP 8.2

### Possible Solution

Add require for SimpleRESTAdapterBundle for PHP 8.2 in composer.json

**Comment by betterapp** [comment]
https://github.com/BrandOriented/PimcoreCiHubConnector/pull/12

**Comment by labudzinski** [comment]
Pull request has been merged
