### ISSUE TITLE
No workspace and delivery settings tab

### ISSUE THREAD

**Issue by Stefan-JustMe69-SQ** [BrandOriented/SimpleRESTAdapterBundle#18]
### Pimcore version(s) affected

11.1.5

### Description

Hi,
I'm using pimcore 11 and actual versions of [PimcoreCiHubConnector](https://github.com/BrandOriented/PimcoreCiHubConnector) and [PimcoreCIHubAdapterBundle](https://github.com/BrandOriented/PimcoreCIHubAdapterBundle)

After updating to V 3.0.6 (Connector) there is no tab in pimcore backend anymore on CI-hub configuration 'workspace' and 'delivery settings' as shown in your pictures.
So I'm not able to define api-key and connot use CI-Hub as I cannot define the token for usage?

Please help/advise

### How to reproduce

install / configure pimcore 11 and both bo-hub plugins

create new datahub entry ci-hub in pimcore backend
no workspace-tab and no delivery-settings tab visible

**Comment by labudzinski** [comment]
<img width="984" alt="Screenshot 2024-02-21 at 09 54 40" src="https://github.com/BrandOriented/PimcoreCiHubConnector/assets/1152480/596ff211-5a73-4afd-87f7-7daaf368e836">
<img width="827" alt="Screenshot 2024-02-21 at 09 54 25" src="https://github.com/BrandOriented/PimcoreCiHubConnector/assets/1152480/ca8b99ab-087a-4f23-9756-0456be7e27f9">

The current version is based on full pimcore permissions - that is, workspace is configured in the Users tab.
The token is now located both in the Users tab as well as in "My Profile"
