### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by labudzinski** [BrandOriented/SimpleRESTAdapterBundle#26]
### Pimcore version(s) affected

3.0.0

### Description

After selecting filters, it should show assets that meet the filtering criteria and there should be no deviation from that. Currently, after selecting filters, it shows nothing.
It should be possible to select more than one filter and no errors should pop up as a result. Currently, after selecting more than one filter, it pops up "GET /api/v1/assets/folder failed: Error: GET /tree-items failed: Internal Server Error (500)"

Also, no request is sent to the API, after choice any filter value.

### How to reproduce

Choose a filter value in the CIHUB Plugin

**Comment by wkania** [comment]
[The very first time Elasticsearch finds a new field whose mapping is not pre-defined inside the index, it automatically tries to guess the data type and analyzer of that field and set its default value.](https://opster.com/analysis/elasticsearch-missing-meta-field-in-mapping-of-index/)


@labudzinski  We do not set mappings for the fields that we filter. This is the cause of why the filters sometimes do not work.
