### ISSUE TITLE
Image preview not updated immediately after update in Pimcore

### ISSUE THREAD

**Issue by betterapp** [BrandOriented/SimpleRESTAdapterBundle#43]
### Pimcore version(s) affected

11

### Description

We have some images in Pimcore Assets.

When we upload new version of the image or publish some other version from versions tab the image is updated in Pimcore.
Request image data also have new version image content.
![image](https://github.com/BrandOriented/PimcoreCiHubConnector/assets/7449124/d9dfec7e-9010-47da-b3ac-6f3f9e389824)

But in asset list panel in CI-HUB in InDesign I see old images.
![image](https://github.com/BrandOriented/PimcoreCiHubConnector/assets/7449124/35bd39c3-23f5-412f-a1ed-a7eb39d4f11f)

They are refreshed after about 5 min. Why they are not refreshed immediately after reload folder ?

### How to reproduce

1. Upload some images under Pimcore
2. Load them in CI-HUB panel under InDesign
3. Upload new image version for one image.
4. Reload image list in CI-HUB in InDesign.

**Comment by labudzinski** [comment]
@betterapp 

On the RestHelperTrait, we have a function to cache headers for thumbnails, which is used on the DownloadController on line 229.

`protected function addThumbnailCacheHeaders(Response $response): void
    {
        $lifetime = 300;
        $dateTime = new \DateTime('now');
        $dateTime->add(new \DateInterval('PT'.$lifetime.'S'));

        $response->setMaxAge($lifetime);
        $response->setPublic();
        $response->setExpires($dateTime);
        $response->headers->set('Pragma', '');
    }`

**Comment by betterapp** [comment]
ok
