### ISSUE TITLE
No method available: `getCommonProperties`

### ISSUE THREAD

**Issue by NiklasBr** [BrandOriented/SimpleRESTAdapterBundle#54]
https://github.com/BrandOriented/PimcoreCiHubConnector/blob/d1be407acfbe035ba161f5d1d6d3c20a84df47cc/src/Elasticsearch/Mapping/DataObjectMapping.php#L23

Can't find `getCommonProperties()` anywhere in the code base unfortunately. Is it supposed to be something else?

**Comment by betterapp** [comment]
@NiklasBr 
it is defined in parent class here

vendor/bo-hub/ci-hub-api-bundle/src/Elasticsearch/Mapping/DefaultMapping.php

**Comment by NiklasBr** [comment]
@betterapp please show me which line `getCommonProperties()` is! 

![image](https://github.com/BrandOriented/PimcoreCiHubConnector/assets/279826/4bf30431-2acb-4d2f-8db3-3f966631f871)

When I look at https://github.com/BrandOriented/PimcoreCiHubConnector/blob/master/src/Elasticsearch/Mapping/DefaultMapping.php

I only see these methods:

![Screenshot 2024-05-23 at 14 54 38](https://github.com/BrandOriented/PimcoreCiHubConnector/assets/279826/68e37cb9-2026-4b14-a6bd-897f951ccf3a)

**Comment by betterapp** [comment]
Hmmm

You are right: In 3.0.16 it exists.

**Comment by betterapp** [comment]
@labudzinski

As I see it was removed in 3.0.17
https://github.com/BrandOriented/PimcoreCiHubConnector/commit/0a2cc97498fe703e739136a35b9034e8f17697b5#diff-ea69977ad2ffff202639a4b7de42c8b612dddf30d8b3857a1e53210b12fb5684L43

But call the method is not removed (or maybe the method should not be removed ?)
I do not know the context of the PR

**Comment by NiklasBr** [comment]
What should we do @betterapp?

**Comment by betterapp** [comment]
@NiklasBr 

I do not know if call of this method should be just removed ? That mean the ES schema was changed ?
I do not know the context of the PR.

@labudzinski

**Comment by labudzinski** [comment]
The method used to create the ES index has been changed to be more explicit. 
Fixed deficiencies in code.
