### ISSUE TITLE
Results "cogwheel" menu is being clipped

### ISSUE THREAD

**Issue by NiklasBr** [BrandOriented/SimpleRESTAdapterBundle#55]
### Pimcore version(s) affected

11.2.3

### Description

In the plugin window/tabpanel there is a cogwheel with the results, it is always being cut off.  See arrow in attached screen shot.

### How to reproduce

![Screenshot 2024-05-29 at 11 09 27](https://github.com/BrandOriented/PimcoreCiHubConnector/assets/279826/cb2c4ba0-7cb5-492e-8136-6e029dfa8921)

### Additional Context

I tried to submit at https://ci-hub.com/service-help?mv=product&mv2=accc but there were lots of CORS errors preventing the form from working.

**Comment by labudzinski** [comment]
You will need to report any bugs in the plugin to the CI-HUB team at https://ci-hub.com/contact.

**Comment by NiklasBr** [comment]
I'm unable to use the contact form because it throws a CORS security error.
